### ISSUE TITLE
Plugin not playing well downloading pacts from latest pact broker versions

### ISSUE THREAD

**Issue by andreschaffer** [warmuuh/pactbroker-maven-plugin#24]
Hi!

We're getting a json parsing error when downloading pacts from the latest pact broker versions (e.g. docker image dius/pact-broker:2.6.0-2).

```
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 14
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 27 more
```

**Comment by vini46** [comment]
Hi,
even i am facing the same issue, is there any solution for this ?
